### ISSUE TITLE
Kate Editor LSP plugin and groovy-language-server

### ISSUE THREAD

**Issue by xhujerr** [GroovyLanguageServer/groovy-language-server#40]
I'm trying to make groovy-language-server work with the [LSP Client Plugin](https://docs.kde.org/stable5/en/applications/kate/kate-application-plugin-lspclient.html) of the [Kate Editor](https://kate-editor.org/)

I added to my LSP config
```
{
    "servers": {
        ...
        "groovy": {
            "command": ["java", "-jar", "/home/username/bin/groovy-language-server-all.jar"],
            "url": "https://github.com/prominic/groovy-language-server",
            "highlightingModeRegex": "^Groovy$"
        }
    }
}
```
when I start Kate, the command `ps -ef | grep groovy-language-server` returns:
```
username    83122   83066 38 02:40 pts/8    00:00:02 /usr/bin/java -jar /home/username/bin/groovy-language-server-all.jar
```
so the server starts. But I don't see the features (symbols .. etc) in the editor.

I also use `python-language-server` and I can see the features for the python files. So the Kate LSP plugin in general works.

Any hints how can I troubleshoot it?
How do I enable debug in groovy-language-server?

**Comment by raphj** [comment]
Same here. The diagnostics panel does pick up errors in random groovy files lying in my home directory but not necessarily the currently opened file. It's like if Kate was not able to communicate the current file to groovy-language-server (if that makes sense in the protocol, I don't know anything about LSP).

**Comment by matthew11** [comment]
I also have the random errors from groovy files in my home directory as well, but only initially. After a couple of seconds the symbols pane get populated, and looks like the LSP functions are working fine. If I edit the document the diagnostics panel got cleared, and only shows errors related to the current file.
I'm using Kate 22.04.0.

**Comment by matthew11** [comment]
Figured out, just add
"root": "."
line to the configuration to specify the scope of the validation. It also speeds up the server a lot.
