### ISSUE TITLE
Render Groovydoc in hover for classes, methods and fields.

### ISSUE THREAD

**Issue by shadycuz** [GroovyLanguageServer/groovy-language-server#50]
This is a feature that I think would make a big impact and I'm excited to try and implement it. Unfortunately, I'm not the best java/groovy developer. So I think it makes sense to do a bit of planning before hand. I looked at how we are getting the AST currently and I did not find a way to extract the comments. Here are some ways I think it could be implemented. 

## Using a different parser to create the AST.
The [parrot](https://github.com/danielsun1106/groovy-parser) parser seems to support comments and probably would be the easiest way for me to implement this feature. But I understand that changing the parser would probably be a ton of work to the rest of the library so its probably not a good choice.

## Parsing twice?
I found this [GroovyDoc](http://docs.groovy-lang.org/latest/html/api/org/codehaus/groovy/tools/groovydoc/GroovyDocTool.html) package. I guess we could parse with it as well and have it extract out the comments? 

Let me know if you have any other ideas.

**Comment by joshtynjala** [comment]
I wonder if Groovy 3 exposes the doc comments or not? I'm waiting on them to release a particular bug fix before I upgrade to Groovy 3. I know some of the APIs have improved, but I haven't had much chance to dive in very deeply. I only learned enough of the new API to get the current features of the language server working (minus one or two that need that bug fix).

**Comment by shadycuz** [comment]
@joshtynjala coolio, I will focus on a Groovy 3 implementation. Let me do some research in the day or two and get back to you.

**Comment by shadycuz** [comment]
@joshtynjala So the first sentence of the Groovy3 [release notes](https://groovy-lang.org/releasenotes/groovy-3.0.html) talks about switching to `parrot`. 

Parrot for sure offers javadoc comments when it creates the AST. Does that mean when we switch to groovy 3 we will have access to parrot? If so then implementing this will be a lot easier.

**Comment by joshtynjala** [comment]
Yeah, with that in mind, it sounds like implementing this will be much easier with Groovy 3.

**Comment by shadycuz** [comment]
This was further down the page "runtime groovydoc, i.e. groovydoc with @Groovydoc; groovydoc attached to AST node as metadata"

@joshtynjala So it seems like annotated groovy doc will be there, I'm not sure about normal groovydoc? I should be able to create a feature branch off of the `groovy3` branch and see if normal comments work correctly right?

**Comment by shadycuz** [comment]
From the parrot docs

> groovy.attach.runtime.groovydoc: whether to attach @Groovydoc annotation to all members which have groovydoc(i.e. /**@ ... */)

So it seems like a way exists to force parrot to treat all groovy-doc like its runtime.

**Comment by joshtynjala** [comment]
Yeah, feel free create a branch off the groovy3 branch and see what you can find.
