### ISSUE TITLE
Error: Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by shadycuz** [GroovyLanguageServer/groovy-language-server#52]
I have been seeing this error in the logs of vscode for [sometime](https://github.com/DontShaveTheYak/groovy-guru/issues/12). Eventually I tracked it down to the [client side](https://github.com/microsoft/vscode-languageserver-node/issues/797) of the lsp. They explained that negative line numbers are not allowed in the LSP and told me it must be coming from the server.

I did a search and it seems like we assign `-1` to lots of places. I stumbled across this method [here](https://github.com/GroovyLanguageServer/groovy-language-server/blob/6ccf73b938d0254ed85501d1e9fdb343c64ec7ff/src/main/java/net/prominic/groovyls/util/GroovyLanguageServerUtils.java#L39-L49). Which seemed like it could be a potential place to fix this.

I really struggled in debugging this. I first tried printing the values out if they were less than 0, but since the LSP communicates by stdout/stdin that would just crash the client =/. I then tried attaching a debugger by commenting out the line in the client extension but that didn't see to do anything after it connected (break points didn't work etc.). Any debugging tips would be greatly appreciated.

Eventually I just set any line or column numbers less than 0 to 0 and that made my errors go away. I havent submitted a PR because I wasnt sure this was the best place to fix this issue. I also wasn't sure if and other IDE's were relying on this behavior. Let me know if I should submit a PR with my quick and dirty fix or if you have better idea where this could be handled.

**Comment by joshtynjala** [comment]
> I first tried printing the values out if they were less than 0, but since the LSP communicates by stdout/stdin that would just crash the client =/

`System.err` will work.

**Comment by shadycuz** [comment]
`"groovy.trace.server": "verbose"` also helped. 

I'm using a fix for this in my fork. https://github.com/DontShaveTheYak/groovy-language-server/commit/10f68522083e07f8bc6a978e1894392ee68188c6

If you want this here, then let me know and I will open the PR. I'm just not confident this a real fix, seems more like a bandaid.
