### ISSUE TITLE
add support for gradle 

### ISSUE THREAD

**Issue by 354651432** [GroovyLanguageServer/groovy-language-server#59]
add support for gradle , lsp cannot find jar packages downloaded by gradle from maven repos

**Comment by joshtynjala** [comment]
This is unlikely to happen any time soon. In the meantime, the `groovy.classpath` setting can be used to add jar packages.

**Comment by 354651432** [comment]
only can add all dependencies one by one . i want a automatic solution

**Comment by joshtynjala** [comment]
Yes, I understand that you want an automatic solution. That's not possible yet, so I gave you the best manual workaround that's available right now. 😺

**Comment by lgranie** [comment]
something like this ?
CLASSPATH=$(~/opt/gradle-classpath-1.2.0/bin/gradle-classpath --gradle-home="~/opt/gradle-7.5.1")
java -Dgroovy.classpath="${CLASSPATH}" -jar "~/opt/groovy-language-server/build/libs/groovy-language-server-all.jar"
