### ISSUE TITLE
Integrate groovy-language-server in a maven project

### ISSUE THREAD

**Issue by adrbessy** [GroovyLanguageServer/groovy-language-server#65]
Hello,
Would it be possible to turn groovy-language-server into a maven project ?
I would like to integrate it in my maven project.
Thank you.

**Comment by joshtynjala** [comment]
I assume that it would be relatively easy for you to fork it, create a pom.xml, and translate the dependencies from the build.gradle file.

**Comment by adrbessy** [comment]
Thank you.
