### ISSUE TITLE
Publish as maven artifact

### ISSUE THREAD

**Issue by SSNikolaevich** [GroovyLanguageServer/groovy-language-server#72]
Your server provides great configuration posibilities that allows to integrate it to custom environment, such as provide custom class loader for code completion, lsp proxy etc. but unfortunately it is not published to the Central Repository what make it difficult to include to build.

**Comment by joshtynjala** [comment]
At this time, we have no plans to publish a release of this project to Maven Central or anywhere else.

**Comment by williamboman** [comment]
@joshtynjala Hey, would you be open to tagging versions in the git repo? This would allow it to be added to https://github.com/mason-org/mason-registry. Any tag would do really, perhaps the current date? (I took a quick peek and it doesn't seem like the language server implementation is versioned).
