### ISSUE TITLE
LSP attach project docs support

### ISSUE THREAD

**Issue by jesusdpa1** [GroovyLanguageServer/groovy-language-server#75]
Hi, 

I am trying to set up nvim to detect the qupath-javadocs.jar using the following .lua file: ftplugin/groovy.lua

```lua
local lspconfig = require('lspconfig')
local mason_registry = require("mason-registry")

local function setup()
    local groovyls_pkg = mason_registry.get_package("groovy-language-server")
    local groovyls_path = groovyls_pkg:get_install_path()

    local home_directory = os.getenv('HOME')
    local javadocs_jar = home_directory .. '/.docs/qupath/qupath-0.4.3-javadoc.jar'

  lspconfig.groovyls.setup {
    cmd = {
      "java",
      "-jar",
      groovyls_path .. '/build/libs/groovy-language-server-all.jar',
      "-Dgroovy.attach.source=true",
      "-Dgroovy.attach.docs=" .. javadocs_jar,
    },
    filetypes = {
      "groovy",
    },
  }
end

return {
    setup = setup,
}

```

but I am getting unable to resolve class QPEx when importing the class QPEx

https://qupath.github.io/javadoc/docs/qupath/lib/gui/scripting/QPEx.html

I installed groovy_ls through lsp-zero, and it is located in the mason/packages/ folder

Is this task possible with groovy_ls?

**Comment by joshtynjala** [comment]
The language server calls the `getGroovydoc()` method of the `org.codehaus.groovy.ast.AnnotatedNode` class defined in _groovy.jar_. I don't know how to change the way that Groovy populates the result of `getGroovydoc()`, or if there's a separate API that can get docs the way that you've configured them.

**Comment by jesusdpa1** [comment]
Thanks! I'll try this method
