### ISSUE TITLE
Autocompletion support for java

### ISSUE THREAD

**Issue by MartinKayJr** [GroovyLanguageServer/groovy-language-server#76]
What I want to do is to inject the prompts I want by default in the prompt, such as all classes and methods in the JDK, as well as the classes and methods I want and other members.

**Comment by joshtynjala** [comment]
Can you give some more detailed examples of what you want?

**Comment by MartinKayJr** [comment]
![image](https://github.com/GroovyLanguageServer/groovy-language-server/assets/37266273/bd9ee324-1671-4f0b-b059-3dabe6a0e6fc)

In the above code, he can only identify members of System, but not members of System.out

**Comment by MartinKayJr** [comment]
![image](https://github.com/GroovyLanguageServer/groovy-language-server/assets/37266273/2a12c629-326c-4be2-a5a4-f890b872cd7c)

Can identify members of System class

**Comment by MartinKayJr** [comment]
Can this problem be solved?

**Comment by MartinKayJr** [comment]
okay, how long will this process take approximately?

**Comment by joshtynjala** [comment]
I do not know. It'll be when I have some extra time. To be honest, it's probably best to assume that it won't happen soon.

**Comment by MartinKayJr** [comment]
OK, looking forward to your improvement
