### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by raxod502-plaid** [GroovyLanguageServer/groovy-language-server#87]
Is there any documentation for this project? The README does not say anything other than how to compile it, and the repository URL links to what appears to be an unrelated IDE project.

Ideally, there should be reference documentation on the expected behavior and features of this language server, what configuration options it supports, expected project layout, dependency resolution behavior, and so on.

For example, there is a reference to a `groovy.classpath` option in https://github.com/GroovyLanguageServer/groovy-language-server/issues/83#issuecomment-1875745308 which it seems would be impossible to discover except by reading the source code.

**Comment by joshtynjala** [comment]
Sorry, no docs besides these READMEs.

https://github.com/GroovyLanguageServer/groovy-language-server/blob/master/README.md
https://github.com/GroovyLanguageServer/groovy-language-server/blob/master/sublime-text/README.md

Besides the Sublime Text README, there's also a sample VSCode extension, both of which may help provide clues how to set up the language server in other IDEs/editors.

https://github.com/GroovyLanguageServer/groovy-language-server/tree/master/vscode-extension
